Update code-freeze.yml

diff --git a/.github/workflows/code-freeze.yml b/.github/workflows/code-freeze.yml
--- a/.github/workflows/code-freeze.yml
+++ b/.github/workflows/code-freeze.yml
@@ -32,11 +32,16 @@ jobs:
         echo $BRANCH_NAME
         echo $PR_TITLE
 
+        # if it's not a critical fix
         if ! [[ "$PR_TITLE" == fix\(critical\):* ]]; then
-          if [[ -z $UNFROZEN_PREFIX ]];
-            then
-              echo "Error: You can only merge PRs titled with prefix 'fix(critical): '."
-            else
+          # and there's an unfrozen prefix
+          if ! [[ -z $UNFROZEN_PREFIX ]]; then
+            # check if the branch matches unfrozen prefix
+            if [[ "$BRANCH_NAME" != $UNFROZEN_PREFIX* ]]; then
               echo "Error: You can only merge from branches that start with '$UNFROZEN_PREFIX', or PRs titled with prefix 'fix(critical): '."
+            fi
+          # repo is fully frozen
+          else
+            echo "Error: You can only merge PRs titled with prefix 'fix(critical): '."
           fi
         fi
