fix: no unfrozen prefix when variable is not present

diff --git a/.github/workflows/code-freeze.yml b/.github/workflows/code-freeze.yml
--- a/.github/workflows/code-freeze.yml
+++ b/.github/workflows/code-freeze.yml
@@ -32,6 +32,12 @@ jobs:
         echo $BRANCH_NAME
         echo $PR_TITLE
 
+        if [[ $UNFROZEN_PREFIX == '' ]] && 
+           [[ "$PR_TITLE" != fix:* && "$PR_TITLE" != *"[critical]"* ]]; then
+          echo "Error: You can only merge PRs titled with 'fix: ' and containing '[critical]'."
+          exit 1
+        fi
+
         if [[ "$BRANCH_NAME" != $UNFROZEN_PREFIX* ]] && 
            [[ "$PR_TITLE" != fix:* && "$PR_TITLE" != *"[critical]"* ]]; then
           echo "Error: You can only merge from branches that start with '$UNFROZEN_PREFIX', or PRs titled with 'fix: ' and containing '[critical]'."
